### ISSUE TITLE
Cannot destructure property createHash of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by littlemousey** [vvv-v13/nuxt-jwt-starter#4]
There might be something wrong with the dependencies. When I clone the project, install node packages with `npm i` and run `npm run dev` I get the following error:

```
 ERROR  Cannot destructure property createHash of 'undefined' or 'null'.
  at Object.<anonymous> (node_modules/extract-css-chunks-webpack-plugin/dist/index.js:27:5)
  at Module._compile (internal/modules/cjs/loader.js:689:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
  at Module.load (internal/modules/cjs/loader.js:599:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
  at Function.Module._load (internal/modules/cjs/loader.js:530:3)
  at Module.require (internal/modules/cjs/loader.js:637:17)
  at require (internal/modules/cjs/helpers.js:22:18)
  at Object.<anonymous> (node_modules/extract-css-chunks-webpack-plugin/dist/cjs.js:3:18)
  at Module._compile (internal/modules/cjs/loader.js:689:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
  at Module.load (internal/modules/cjs/loader.js:599:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
  at Function.Module._load (internal/modules/cjs/loader.js:530:3)
  at Module.require (internal/modules/cjs/loader.js:637:17)
  at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by vvv-v13** [comment]
I have updated version of webpack, please check again

**Comment by littlemousey** [comment]
Great! Thanks, it works now :)
